// <auto-generated />
namespace GymApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddTicketsandTicketsTypes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTicketsandTicketsTypes));
        
        string IMigrationMetadata.Id
        {
            get { return "201811271722408_Add Tickets and Tickets Types"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
